on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: install mockgen
        run: GO111MODULE=on go get github.com/golang/mock/mockgen@latest
      - name: generate mocks
        run: go generate gen.go
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test ./...
